# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(GMOCK_MAIN_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(GMOCK_MAIN_INCLUDE_DIRS)
   
set(GMOCK_MAIN_LIBRARIES
  ${ROOT_DIR}/lib/libgmock_main.so
  CACHE STRING "" FORCE)

mark_as_advanced(GMOCK_MAIN_LIBRARIES)
 
set(GMOCK_MAIN_PACKAGE_FOUND TRUE CACHE INTERNAL "" FORCE)
 
set(GMOCK_MAIN_DEPENDS "GMOCK;PTHREAD" CACHE INTERNAL "" FORCE)
 