# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(DISASM_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(DISASM_INCLUDE_DIRS)
   
set(DISASM_LIBRARIES
  ${ROOT_DIR}/lib/libdisasm.a
  CACHE STRING "" FORCE)

mark_as_advanced(DISASM_LIBRARIES)
 
set(DISASM_PACKAGE_FOUND TRUE CACHE INTERNAL "" FORCE)
 
set(DISASM_DEPENDS "" CACHE INTERNAL "" FORCE)
 