#!/bin/bash
realpath=`readlink -fn $0`
export MKE2FS_CONFIG=/home/vlad/studies/Robocup2019/ctc-linux64-atom-2.8.2.15/yocto-sdk/sysroots/x86_64-naoqisdk-linux/etc/mke2fs.conf
exec -a `dirname $realpath`/mke2fs `dirname $realpath`/mke2fs.real "$@"
