# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(QITESTUTILS_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(QITESTUTILS_INCLUDE_DIRS)
   
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QITESTUTILS DEFAULT_MSG
  QITESTUTILS_INCLUDE_DIRS
)
set(QITESTUTILS_PACKAGE_FOUND ${QITESTUTILS_FOUND} CACHE INTERNAL "" FORCE)
 
set(QITESTUTILS_DEPENDS "qi" CACHE INTERNAL "" FORCE)
 