/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/opennao/jenkins/workspace/yocto-rootfs/build/tmp/sysroots/x86_64-linux/usr/bin/perl-native/perl5.22.1.real bin/enc2xs -Q -O -o def_t.c -f def_t.fnm
 enc2xs VERSION 2.17
*/
extern encode_t ascii_encoding;
extern encode_t ascii_ctrl_encoding;
extern encode_t iso_8859_1_encoding;
extern encode_t null_encoding;
