/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/opennao/jenkins/workspace/yocto-rootfs/build/tmp/sysroots/x86_64-linux/usr/bin/perl-native/perl5.22.1.real ../bin/enc2xs -Q -o ir_04_t.c -f ir_04_t.fnm
 enc2xs VERSION 2.17
*/
extern encode_t iso_ir_165_encoding;
