set(PTHREAD_LIBRARIES
  ${YOCTO_SDK_TARGET_SYSROOT}/usr/lib/libpthread.so
  CACHE INTERNAL "" FORCE
)

set(PTHREAD_INCLUDE_DIRS
  ${ALDE_CTC_SYSROOT}/usr/include
  CACHE INTERNAL "" FORCE
)

qi_persistent_set(PTHREAD_DEPENDS)
export_lib(PTHREAD)
