get_filename_component(_opencv3_stitching_root "${YOCTO_SDK_TARGET_SYSROOT}" ABSOLUTE)

set(
  OPENCV3_STITCHING_LIBRARIES
  ${_opencv3_stitching_root}/usr/lib/libopencv_stitching.so
  CACHE INTERNAL "" FORCE
)

set(
  OPENCV3_STITCHING_INCLUDE_DIRS
  ${_opencv3_stitching_root}/usr/include
  CACHE INTERNAL "" FORCE
)

qi_persistent_set(OPENCV3_STITCHING_DEPENDS OPENCV3_CORE OPENCV3_FLANN OPENCV3_IMGPROC OPENCV3_FEATURES2D OPENCV3_CALIB3D OPENCV3_GPU OPENCV3_NONFREE PTHREAD)

export_lib(OPENCV3_STITCHING)
