get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)


set(CHUNKWARE_SIMPLE_DYNAMICS_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(CHUNKWARE_SIMPLE_DYNAMICS_INCLUDE_DIRS)

set(CHUNKWARE_SIMPLE_DYNAMICS_LIBRARIES "${ROOT_DIR}/lib/libchunkware_simple_dynamics.so;" CACHE STRING "" FORCE)
mark_as_advanced(CHUNKWARE_SIMPLE_DYNAMICS_LIBRARIES)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHUNKWARE_SIMPLE_DYNAMICS DEFAULT_MSG
  CHUNKWARE_SIMPLE_DYNAMICS_LIBRARIES
  CHUNKWARE_SIMPLE_DYNAMICS_INCLUDE_DIRS
)
set(CHUNKWARE_SIMPLE_DYNAMICS_PACKAGE_FOUND ${CHUNKWARE_SIMPLE_DYNAMICS_FOUND} CACHE INTERNAL "" FORCE)

set(CHUNKWARE_SIMPLE_DYNAMICS_DEPENDS "" CACHE INTERNAL "" FORCE)
