get_filename_component(_opencv3_legacy_root "${YOCTO_SDK_TARGET_SYSROOT}" ABSOLUTE)

set(
  OPENCV3_LEGACY_LIBRARIES
  ${_opencv3_legacy_root}/usr/lib/libopencv_legacy.so
  CACHE INTERNAL "" FORCE
)

set(
  OPENCV3_LEGACY_INCLUDE_DIRS
  ${_opencv3_legacy_root}/usr/include
  CACHE INTERNAL "" FORCE
)

qi_persistent_set(OPENCV3_LEGACY_DEPENDS OPENCV3_CORE OPENCV3_IMGPROC OPENCV3_HIGHGUI OPENCV3_FEATURES2D OPENCV3_CALIB3D OPENCV3_ML OPENCV3_VIDEO PTHREAD)

export_lib(OPENCV3_LEGACY)
