get_filename_component(_opencv3_videostab_root "${YOCTO_SDK_TARGET_SYSROOT}" ABSOLUTE)

set(
  OPENCV3_VIDEOSTAB_LIBRARIES
  ${_opencv3_videostab_root}/usr/lib/libopencv_videostab.so
  CACHE INTERNAL "" FORCE
)

set(
  OPENCV3_VIDEOSTAB_INCLUDE_DIRS
  ${_opencv3_videostab_root}/usr/include
  CACHE INTERNAL "" FORCE
)

qi_persistent_set(OPENCV3_VIDEOSTAB_DEPENDS OPENCV3_CORE OPENCV3_IMGPROC OPENCV3_HIGHGUI OPENCV3_FEATURES2D OPENCV3_VIDEO OPENCV3_PHOTO OPENCV3_GPU PTHREAD)

export_lib(OPENCV3_VIDEOSTAB)
