/*  DO NOT EDIT THIS FILE.

    It has been auto-edited by fixincludes from:

	"/home/opennao/jenkins/workspace/yocto-rootfs/build/tmp/sysroots/ald-atom/usr/include/msgpack/predef/os/linux.h"

    This had to be done to correct non-standard usages in the
    original, manufacturer supplied header file.  */

/*
Copyright Rene Rivera 2008-2015
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
*/

#ifndef MSGPACK_PREDEF_OS_LINUX_H
#define MSGPACK_PREDEF_OS_LINUX_H

#include <msgpack/predef/version_number.h>
#include <msgpack/predef/make.h>

/*`
[heading `MSGPACK_OS_LINUX`]

[@http://en.wikipedia.org/wiki/Linux Linux] operating system.

[table
    [[__predef_symbol__] [__predef_version__]]

    [[`linux`] [__predef_detection__]]
    [[`__linux`] [__predef_detection__]]
    ]
 */

#define MSGPACK_OS_LINUX MSGPACK_VERSION_NUMBER_NOT_AVAILABLE

#if !defined(MSGPACK_PREDEF_DETAIL_OS_DETECTED) && ( \
    defined(__linux__) || defined(__linux) \
    )
#   undef MSGPACK_OS_LINUX
#   define MSGPACK_OS_LINUX MSGPACK_VERSION_NUMBER_AVAILABLE
#endif

#if MSGPACK_OS_LINUX
#   define MSGPACK_OS_LINUX_AVAILABLE
#   include <msgpack/predef/detail/os_detected.h>
#endif

#define MSGPACK_OS_LINUX_NAME "Linux"

#endif

#include <msgpack/predef/detail/test.h>
MSGPACK_PREDEF_DECLARE_TEST(MSGPACK_OS_LINUX,MSGPACK_OS_LINUX_NAME)
